name: Build Website
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Setup Node Version
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        cp .env.example .env
        yarn install --ignore-engines
        yarn build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }} 
        folder: build # The folder the action should deploy.
        branch: gh-pages
